/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const ProductOrder = IDL.Record({
  'id' : IDL.Nat32,
  'status' : OrderStatus,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'productId' : IDL.Nat32,
  'amount' : IDL.Nat64,
  'isAutoDelivery' : IDL.Bool,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'nagad' : IDL.Null,
  'bkash' : IDL.Null,
});
export const WalletTopUpTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'amount' : IDL.Nat64,
  'transactionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'price' : IDL.Nat64,
  'isAutoDelivery' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([IDL.Text, IDL.Nat64, IDL.Bool], [IDL.Nat32], []),
  'approveWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([IDL.Nat32], [IDL.Nat32], []),
  'deleteProduct' : IDL.Func([IDL.Nat32], [], []),
  'getAllOrdersSortedByTime' : IDL.Func([], [IDL.Vec(ProductOrder)], ['query']),
  'getAllWalletTopUpTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTopUpTransaction)],
      ['query'],
    ),
  'getCallerBalance' : IDL.Func([], [IDL.Nat64], ['query']),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(ProductOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWalletTopUpTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTopUpTransaction)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWalletTopUpTransaction' : IDL.Func(
      [IDL.Nat64, PaymentMethod, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat32, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat32, IDL.Text, IDL.Nat64, IDL.Bool],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProductOrder = IDL.Record({
    'id' : IDL.Nat32,
    'status' : OrderStatus,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'productId' : IDL.Nat32,
    'amount' : IDL.Nat64,
    'isAutoDelivery' : IDL.Bool,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'nagad' : IDL.Null, 'bkash' : IDL.Null });
  const WalletTopUpTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'amount' : IDL.Nat64,
    'transactionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'price' : IDL.Nat64,
    'isAutoDelivery' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([IDL.Text, IDL.Nat64, IDL.Bool], [IDL.Nat32], []),
    'approveWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([IDL.Nat32], [IDL.Nat32], []),
    'deleteProduct' : IDL.Func([IDL.Nat32], [], []),
    'getAllOrdersSortedByTime' : IDL.Func(
        [],
        [IDL.Vec(ProductOrder)],
        ['query'],
      ),
    'getAllWalletTopUpTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTopUpTransaction)],
        ['query'],
      ),
    'getCallerBalance' : IDL.Func([], [IDL.Nat64], ['query']),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(ProductOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWalletTopUpTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTopUpTransaction)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWalletTopUpTransaction' : IDL.Func(
        [IDL.Nat64, PaymentMethod, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat32, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat32, IDL.Text, IDL.Nat64, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };