/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type PaymentMethod = { 'nagad' : null } |
  { 'bkash' : null };
export interface Product {
  'id' : number,
  'name' : string,
  'price' : bigint,
  'isAutoDelivery' : boolean,
}
export interface ProductOrder {
  'id' : number,
  'status' : OrderStatus,
  'createdAt' : Time,
  'user' : Principal,
  'productId' : number,
  'amount' : bigint,
  'isAutoDelivery' : boolean,
}
export type Time = bigint;
export type TransactionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTopUpTransaction {
  'id' : string,
  'status' : TransactionStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : Principal,
  'amount' : bigint,
  'transactionId' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, bigint, boolean], number>,
  'approveWalletTopUpTransaction' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[number], number>,
  'deleteProduct' : ActorMethod<[number], undefined>,
  'getAllOrdersSortedByTime' : ActorMethod<[], Array<ProductOrder>>,
  'getAllWalletTopUpTransactions' : ActorMethod<
    [],
    Array<WalletTopUpTransaction>
  >,
  'getCallerBalance' : ActorMethod<[], bigint>,
  'getCallerOrders' : ActorMethod<[], Array<ProductOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWalletTopUpTransactions' : ActorMethod<
    [],
    Array<WalletTopUpTransaction>
  >,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectWalletTopUpTransaction' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitWalletTopUpTransaction' : ActorMethod<
    [bigint, PaymentMethod, string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[number, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[number, string, bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];