/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboard {
  'totalAdProfit' : bigint,
  'totalDiamonds' : bigint,
  'totalUsers' : bigint,
  'totalPoints' : bigint,
  'totalRevenue' : bigint,
}
export interface ConversionSettings {
  'pointsToDiamondsRate' : bigint,
  'diamondsPerPackage' : bigint,
  'bdtToPointsRate' : bigint,
}
export interface DiamondPurchase {
  'id' : string,
  'packageName' : string,
  'createdAt' : Time,
  'user' : Principal,
  'diamondsAwarded' : bigint,
  'pointsDeducted' : bigint,
}
export type PaymentMethod = { 'nagad' : null } |
  { 'bkash' : null };
export interface PointsPurchaseRequest {
  'id' : string,
  'status' : PointsPurchaseStatus,
  'createdAt' : Time,
  'user' : Principal,
  'amount' : bigint,
  'bdtAmount' : bigint,
}
export type PointsPurchaseStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PointsTransaction {
  'id' : string,
  'transactionType' : PointsTransactionType,
  'metadata' : string,
  'createdAt' : Time,
  'user' : Principal,
  'amount' : bigint,
}
export type PointsTransactionType = { 'adReward' : null } |
  { 'adminAdjustment' : null } |
  { 'spend' : null } |
  { 'purchase' : null };
export interface Product {
  'id' : number,
  'name' : string,
  'price' : bigint,
  'isAutoDelivery' : boolean,
}
export type Time = bigint;
export type TransactionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTopUpTransaction {
  'id' : string,
  'status' : TransactionStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : Principal,
  'amount' : bigint,
  'transactionId' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, bigint, boolean], number>,
  'approvePointsPurchaseRequest' : ActorMethod<[string], boolean>,
  'approveWalletTopUpTransaction' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdReward' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[number], undefined>,
  'getAdRewardsAnalytics' : ActorMethod<
    [],
    { 'totalProfit' : bigint, 'totalAdRewards' : bigint }
  >,
  'getAdminDashboard' : ActorMethod<[], AdminDashboard>,
  'getAllDiamondPurchases' : ActorMethod<[], Array<DiamondPurchase>>,
  'getAllPointsPurchaseRequests' : ActorMethod<
    [],
    Array<PointsPurchaseRequest>
  >,
  'getAllPointsTransactions' : ActorMethod<[], Array<PointsTransaction>>,
  'getAllWalletTopUpTransactions' : ActorMethod<
    [],
    Array<WalletTopUpTransaction>
  >,
  'getCallerBalance' : ActorMethod<[], bigint>,
  'getCallerDailyAdCount' : ActorMethod<[], bigint>,
  'getCallerDiamondPurchases' : ActorMethod<[], Array<DiamondPurchase>>,
  'getCallerPointsBalance' : ActorMethod<[], bigint>,
  'getCallerPointsPurchaseRequests' : ActorMethod<
    [],
    Array<PointsPurchaseRequest>
  >,
  'getCallerPointsTransactions' : ActorMethod<[], Array<PointsTransaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWalletTransactions' : ActorMethod<
    [],
    Array<WalletTopUpTransaction>
  >,
  'getConversionSettings' : ActorMethod<[], ConversionSettings>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseDiamondsWithPoints' : ActorMethod<[string, string], boolean>,
  'rejectPointsPurchaseRequest' : ActorMethod<[string], boolean>,
  'rejectWalletTopUpTransaction' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAddMoneyTransaction' : ActorMethod<
    [bigint, PaymentMethod, string],
    undefined
  >,
  'submitPointsPurchaseRequest' : ActorMethod<[bigint, string], undefined>,
  'updateConversionSettings' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'updateProduct' : ActorMethod<[number, string, bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];