/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminDashboard = IDL.Record({
  'totalAdProfit' : IDL.Nat64,
  'totalDiamonds' : IDL.Nat64,
  'totalUsers' : IDL.Nat,
  'totalPoints' : IDL.Int,
  'totalRevenue' : IDL.Nat64,
});
export const Time = IDL.Int;
export const DiamondPurchase = IDL.Record({
  'id' : IDL.Text,
  'packageName' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'diamondsAwarded' : IDL.Nat64,
  'pointsDeducted' : IDL.Nat64,
});
export const PointsPurchaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PointsPurchaseRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : PointsPurchaseStatus,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'amount' : IDL.Int,
  'bdtAmount' : IDL.Nat64,
});
export const PointsTransactionType = IDL.Variant({
  'adReward' : IDL.Null,
  'adminAdjustment' : IDL.Null,
  'spend' : IDL.Null,
  'purchase' : IDL.Null,
});
export const PointsTransaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : PointsTransactionType,
  'metadata' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'amount' : IDL.Int,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'nagad' : IDL.Null,
  'bkash' : IDL.Null,
});
export const WalletTopUpTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'amount' : IDL.Nat64,
  'transactionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ConversionSettings = IDL.Record({
  'pointsToDiamondsRate' : IDL.Nat64,
  'diamondsPerPackage' : IDL.Nat64,
  'bdtToPointsRate' : IDL.Nat64,
});
export const Product = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'price' : IDL.Nat64,
  'isAutoDelivery' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([IDL.Text, IDL.Nat64, IDL.Bool], [IDL.Nat32], []),
  'approvePointsPurchaseRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'approveWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdReward' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat32], [], []),
  'getAdRewardsAnalytics' : IDL.Func(
      [],
      [IDL.Record({ 'totalProfit' : IDL.Nat64, 'totalAdRewards' : IDL.Nat })],
      ['query'],
    ),
  'getAdminDashboard' : IDL.Func([], [AdminDashboard], ['query']),
  'getAllDiamondPurchases' : IDL.Func(
      [],
      [IDL.Vec(DiamondPurchase)],
      ['query'],
    ),
  'getAllPointsPurchaseRequests' : IDL.Func(
      [],
      [IDL.Vec(PointsPurchaseRequest)],
      ['query'],
    ),
  'getAllPointsTransactions' : IDL.Func(
      [],
      [IDL.Vec(PointsTransaction)],
      ['query'],
    ),
  'getAllWalletTopUpTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTopUpTransaction)],
      ['query'],
    ),
  'getCallerBalance' : IDL.Func([], [IDL.Nat64], ['query']),
  'getCallerDailyAdCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerDiamondPurchases' : IDL.Func(
      [],
      [IDL.Vec(DiamondPurchase)],
      ['query'],
    ),
  'getCallerPointsBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getCallerPointsPurchaseRequests' : IDL.Func(
      [],
      [IDL.Vec(PointsPurchaseRequest)],
      ['query'],
    ),
  'getCallerPointsTransactions' : IDL.Func(
      [],
      [IDL.Vec(PointsTransaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWalletTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTopUpTransaction)],
      ['query'],
    ),
  'getConversionSettings' : IDL.Func([], [ConversionSettings], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseDiamondsWithPoints' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'rejectPointsPurchaseRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'rejectWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAddMoneyTransaction' : IDL.Func(
      [IDL.Nat64, PaymentMethod, IDL.Text],
      [],
      [],
    ),
  'submitPointsPurchaseRequest' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
  'updateConversionSettings' : IDL.Func(
      [IDL.Nat64, IDL.Nat64, IDL.Nat64],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat32, IDL.Text, IDL.Nat64, IDL.Bool],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminDashboard = IDL.Record({
    'totalAdProfit' : IDL.Nat64,
    'totalDiamonds' : IDL.Nat64,
    'totalUsers' : IDL.Nat,
    'totalPoints' : IDL.Int,
    'totalRevenue' : IDL.Nat64,
  });
  const Time = IDL.Int;
  const DiamondPurchase = IDL.Record({
    'id' : IDL.Text,
    'packageName' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'diamondsAwarded' : IDL.Nat64,
    'pointsDeducted' : IDL.Nat64,
  });
  const PointsPurchaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PointsPurchaseRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : PointsPurchaseStatus,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'amount' : IDL.Int,
    'bdtAmount' : IDL.Nat64,
  });
  const PointsTransactionType = IDL.Variant({
    'adReward' : IDL.Null,
    'adminAdjustment' : IDL.Null,
    'spend' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const PointsTransaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : PointsTransactionType,
    'metadata' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'amount' : IDL.Int,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'nagad' : IDL.Null, 'bkash' : IDL.Null });
  const WalletTopUpTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'amount' : IDL.Nat64,
    'transactionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ConversionSettings = IDL.Record({
    'pointsToDiamondsRate' : IDL.Nat64,
    'diamondsPerPackage' : IDL.Nat64,
    'bdtToPointsRate' : IDL.Nat64,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'price' : IDL.Nat64,
    'isAutoDelivery' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([IDL.Text, IDL.Nat64, IDL.Bool], [IDL.Nat32], []),
    'approvePointsPurchaseRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'approveWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdReward' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat32], [], []),
    'getAdRewardsAnalytics' : IDL.Func(
        [],
        [IDL.Record({ 'totalProfit' : IDL.Nat64, 'totalAdRewards' : IDL.Nat })],
        ['query'],
      ),
    'getAdminDashboard' : IDL.Func([], [AdminDashboard], ['query']),
    'getAllDiamondPurchases' : IDL.Func(
        [],
        [IDL.Vec(DiamondPurchase)],
        ['query'],
      ),
    'getAllPointsPurchaseRequests' : IDL.Func(
        [],
        [IDL.Vec(PointsPurchaseRequest)],
        ['query'],
      ),
    'getAllPointsTransactions' : IDL.Func(
        [],
        [IDL.Vec(PointsTransaction)],
        ['query'],
      ),
    'getAllWalletTopUpTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTopUpTransaction)],
        ['query'],
      ),
    'getCallerBalance' : IDL.Func([], [IDL.Nat64], ['query']),
    'getCallerDailyAdCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerDiamondPurchases' : IDL.Func(
        [],
        [IDL.Vec(DiamondPurchase)],
        ['query'],
      ),
    'getCallerPointsBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getCallerPointsPurchaseRequests' : IDL.Func(
        [],
        [IDL.Vec(PointsPurchaseRequest)],
        ['query'],
      ),
    'getCallerPointsTransactions' : IDL.Func(
        [],
        [IDL.Vec(PointsTransaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWalletTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTopUpTransaction)],
        ['query'],
      ),
    'getConversionSettings' : IDL.Func([], [ConversionSettings], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseDiamondsWithPoints' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'rejectPointsPurchaseRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'rejectWalletTopUpTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAddMoneyTransaction' : IDL.Func(
        [IDL.Nat64, PaymentMethod, IDL.Text],
        [],
        [],
      ),
    'submitPointsPurchaseRequest' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
    'updateConversionSettings' : IDL.Func(
        [IDL.Nat64, IDL.Nat64, IDL.Nat64],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat32, IDL.Text, IDL.Nat64, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };