/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: number;
    name: string;
    price: bigint;
    isAutoDelivery: boolean;
}
export type Time = bigint;
export interface AdminDashboard {
    totalAdProfit: bigint;
    totalDiamonds: bigint;
    totalUsers: bigint;
    totalPoints: bigint;
    totalRevenue: bigint;
}
export interface PointsTransaction {
    id: string;
    transactionType: PointsTransactionType;
    metadata: string;
    createdAt: Time;
    user: Principal;
    amount: bigint;
}
export interface WalletTopUpTransaction {
    id: string;
    status: TransactionStatus;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    user: Principal;
    amount: bigint;
    transactionId: string;
}
export interface DiamondPurchase {
    id: string;
    packageName: string;
    createdAt: Time;
    user: Principal;
    diamondsAwarded: bigint;
    pointsDeducted: bigint;
}
export interface PointsPurchaseRequest {
    id: string;
    status: PointsPurchaseStatus;
    createdAt: Time;
    user: Principal;
    amount: bigint;
    bdtAmount: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface ConversionSettings {
    pointsToDiamondsRate: bigint;
    diamondsPerPackage: bigint;
    bdtToPointsRate: bigint;
}
export enum PaymentMethod {
    nagad = "nagad",
    bkash = "bkash"
}
export enum PointsTransactionType {
    adReward = "adReward",
    adminAdjustment = "adminAdjustment",
    spend = "spend",
    purchase = "purchase"
}
export enum TransactionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(name: string, price: bigint, isAutoDelivery: boolean): Promise<number>;
    approvePointsPurchaseRequest(requestId: string): Promise<boolean>;
    approveWalletTopUpTransaction(transactionId: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimAdReward(transactionId: string): Promise<boolean>;
    deleteProduct(productId: number): Promise<void>;
    getAdRewardsAnalytics(): Promise<{
        totalProfit: bigint;
        totalAdRewards: bigint;
    }>;
    getAdminDashboard(): Promise<AdminDashboard>;
    getAllDiamondPurchases(): Promise<Array<DiamondPurchase>>;
    getAllPointsPurchaseRequests(): Promise<Array<PointsPurchaseRequest>>;
    getAllPointsTransactions(): Promise<Array<PointsTransaction>>;
    getAllWalletTopUpTransactions(): Promise<Array<WalletTopUpTransaction>>;
    getCallerBalance(): Promise<bigint>;
    getCallerDailyAdCount(): Promise<bigint>;
    getCallerDiamondPurchases(): Promise<Array<DiamondPurchase>>;
    getCallerPointsBalance(): Promise<bigint>;
    getCallerPointsPurchaseRequests(): Promise<Array<PointsPurchaseRequest>>;
    getCallerPointsTransactions(): Promise<Array<PointsTransaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWalletTransactions(): Promise<Array<WalletTopUpTransaction>>;
    getConversionSettings(): Promise<ConversionSettings>;
    getProducts(): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    purchaseDiamondsWithPoints(packageName: string, transactionId: string): Promise<boolean>;
    rejectPointsPurchaseRequest(requestId: string): Promise<boolean>;
    rejectWalletTopUpTransaction(transactionId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAddMoneyTransaction(amount: bigint, paymentMethod: PaymentMethod, transactionId: string): Promise<void>;
    submitPointsPurchaseRequest(bdtAmount: bigint, transactionId: string): Promise<void>;
    updateConversionSettings(bdtToPointsRate: bigint, pointsToDiamondsRate: bigint, diamondsPerPackage: bigint): Promise<void>;
    updateProduct(productId: number, name: string, price: bigint, isAutoDelivery: boolean): Promise<boolean>;
}
import type { PaymentMethod as _PaymentMethod, PointsPurchaseRequest as _PointsPurchaseRequest, PointsPurchaseStatus as _PointsPurchaseStatus, PointsTransaction as _PointsTransaction, PointsTransactionType as _PointsTransactionType, Time as _Time, TransactionStatus as _TransactionStatus, UserProfile as _UserProfile, UserRole as _UserRole, WalletTopUpTransaction as _WalletTopUpTransaction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: bigint, arg2: boolean): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2);
            return result;
        }
    }
    async approvePointsPurchaseRequest(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePointsPurchaseRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePointsPurchaseRequest(arg0);
            return result;
        }
    }
    async approveWalletTopUpTransaction(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWalletTopUpTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWalletTopUpTransaction(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimAdReward(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdReward(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAdRewardsAnalytics(): Promise<{
        totalProfit: bigint;
        totalAdRewards: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdRewardsAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdRewardsAnalytics();
            return result;
        }
    }
    async getAdminDashboard(): Promise<AdminDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboard();
            return result;
        }
    }
    async getAllDiamondPurchases(): Promise<Array<DiamondPurchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiamondPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiamondPurchases();
            return result;
        }
    }
    async getAllPointsPurchaseRequests(): Promise<Array<PointsPurchaseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPointsPurchaseRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPointsPurchaseRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPointsTransactions(): Promise<Array<PointsTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPointsTransactions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPointsTransactions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWalletTopUpTransactions(): Promise<Array<WalletTopUpTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWalletTopUpTransactions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWalletTopUpTransactions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerBalance();
            return result;
        }
    }
    async getCallerDailyAdCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDailyAdCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDailyAdCount();
            return result;
        }
    }
    async getCallerDiamondPurchases(): Promise<Array<DiamondPurchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDiamondPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDiamondPurchases();
            return result;
        }
    }
    async getCallerPointsBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPointsBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPointsBalance();
            return result;
        }
    }
    async getCallerPointsPurchaseRequests(): Promise<Array<PointsPurchaseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPointsPurchaseRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPointsPurchaseRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPointsTransactions(): Promise<Array<PointsTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPointsTransactions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPointsTransactions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWalletTransactions(): Promise<Array<WalletTopUpTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWalletTransactions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWalletTransactions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversionSettings(): Promise<ConversionSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversionSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversionSettings();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purchaseDiamondsWithPoints(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseDiamondsWithPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseDiamondsWithPoints(arg0, arg1);
            return result;
        }
    }
    async rejectPointsPurchaseRequest(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPointsPurchaseRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPointsPurchaseRequest(arg0);
            return result;
        }
    }
    async rejectWalletTopUpTransaction(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWalletTopUpTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWalletTopUpTransaction(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitAddMoneyTransaction(arg0: bigint, arg1: PaymentMethod, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAddMoneyTransaction(arg0, to_candid_PaymentMethod_n22(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAddMoneyTransaction(arg0, to_candid_PaymentMethod_n22(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async submitPointsPurchaseRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPointsPurchaseRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPointsPurchaseRequest(arg0, arg1);
            return result;
        }
    }
    async updateConversionSettings(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConversionSettings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConversionSettings(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProduct(arg0: number, arg1: string, arg2: bigint, arg3: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_PaymentMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PointsPurchaseRequest_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointsPurchaseRequest): PointsPurchaseRequest {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PointsPurchaseStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointsPurchaseStatus): PointsPurchaseStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PointsTransactionType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointsTransactionType): PointsTransactionType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PointsTransaction_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointsTransaction): PointsTransaction {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTopUpTransaction_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTopUpTransaction): WalletTopUpTransaction {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionType: _PointsTransactionType;
    metadata: string;
    createdAt: _Time;
    user: Principal;
    amount: bigint;
}): {
    id: string;
    transactionType: PointsTransactionType;
    metadata: string;
    createdAt: Time;
    user: Principal;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_PointsTransactionType_n11(_uploadFile, _downloadFile, value.transactionType),
        metadata: value.metadata,
        createdAt: value.createdAt,
        user: value.user,
        amount: value.amount
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TransactionStatus;
    paymentMethod: _PaymentMethod;
    createdAt: _Time;
    user: Principal;
    amount: bigint;
    transactionId: string;
}): {
    id: string;
    status: TransactionStatus;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    user: Principal;
    amount: bigint;
    transactionId: string;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n16(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n17(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        user: value.user,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PointsPurchaseStatus;
    createdAt: _Time;
    user: Principal;
    amount: bigint;
    bdtAmount: bigint;
}): {
    id: string;
    status: PointsPurchaseStatus;
    createdAt: Time;
    user: Principal;
    amount: bigint;
    bdtAmount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PointsPurchaseStatus_n6(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        user: value.user,
        amount: value.amount,
        bdtAmount: value.bdtAmount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adReward: null;
} | {
    adminAdjustment: null;
} | {
    spend: null;
} | {
    purchase: null;
}): PointsTransactionType {
    return "adReward" in value ? PointsTransactionType.adReward : "adminAdjustment" in value ? PointsTransactionType.adminAdjustment : "spend" in value ? PointsTransactionType.spend : "purchase" in value ? PointsTransactionType.purchase : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nagad: null;
} | {
    bkash: null;
}): PaymentMethod {
    return "nagad" in value ? PaymentMethod.nagad : "bkash" in value ? PaymentMethod.bkash : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "approved" in value ? TransactionStatus.approved : "rejected" in value ? TransactionStatus.rejected : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletTopUpTransaction>): Array<WalletTopUpTransaction> {
    return value.map((x)=>from_candid_WalletTopUpTransaction_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PointsPurchaseRequest>): Array<PointsPurchaseRequest> {
    return value.map((x)=>from_candid_PointsPurchaseRequest_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PointsTransaction>): Array<PointsTransaction> {
    return value.map((x)=>from_candid_PointsTransaction_n9(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentMethod_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    nagad: null;
} | {
    bkash: null;
} {
    return value == PaymentMethod.nagad ? {
        nagad: null
    } : value == PaymentMethod.bkash ? {
        bkash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
